[package]
# Package Information
name = oposs_eltek_sp2
title = OPOSS Eltek Smartpack S
author = Tobias Oetiker <tobi@oetiker.ch>
description = This check monitors Eltek Smartpack S power supply systems via SNMP.

    It tracks power system status, mains voltage, rectifier state,
    load current, and temperature.

# CheckMK Compatibility
version.min_required = 2.3.0p1
version.packaged = 2.3.0p34

# Optional
download_url = https://github.com/oposs/cmk-oposs_eltek_sp2
version.usable_until =

# Build Options
validate_python = true
